# Generated by Django 4.2.5 on 2023-09-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_producto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=200)),
                ("apellidos", models.CharField(max_length=200)),
                ("dni", models.IntegerField(max_length=8)),
                ("telefono", models.IntegerField(max_length=9)),
                ("direccion", models.CharField(max_length=70)),
                ("email", models.CharField(max_length=50)),
                ("fecha_de_nacimiento", models.DateField()),
                (
                    "fecha_de_publicacion",
                    models.DateTimeField(verbose_name="date published"),
                ),
            ],
        ),
    ]
